Continuation (replacement) of #279 : Making results explainable.
the-teachingRSE-project/competencies pull request #283
Opened 2024-06-03 08:02 UTC by hvwaldow

2024-06-04 09:01 UTC, mhagdorn requested changes
I think this is a great addition as it opens another dimension that RSEs need to consider that usually gets brushed under the carpet.

I think the next paragraph in the paper is in comparison relatively weak. Maybe that would be a good place to add some of the ethical concerns coming from the various biases.

2024-06-04 09:03 UTC, mhagdorn commented on competencies.md
> +will have a decisive impact on the adequacy for purpose of the model.
Do we need a reference for adequacy of purpose? This seems to be philosophical term with a specific meaning.

2024-06-09 20:59 UTC, CaptainSifff commented on competencies.md
> +The current trend of an increasing application of computationally irreducible systems, such as those based artificial neural networks,
```suggestion
The current trend of an increasing application of computationally irreducible systems, such as those based on artificial neural networks,
```

2024-06-09 21:02 UTC, CaptainSifff commented on competencies.md
> +The current trend of an increasing application of computationally irreducible systems, such as those based artificial neural networks,
I haven't read Humphreys2004, but can we claim that it's relevant still, although 20 years old?

2024-06-10 08:13 UTC, merged