Add a first extension to the technical pillar intro
the-teachingRSE-project/competencies pull request #290
Opened 2024-06-30 20:37 UTC by MakisH

An attempt to close #288.

Not sure what we agreed on in terms of resources to use, but for now I just followed the [Wikipedia page on Software Engineering](https://en.wikipedia.org/wiki/Software_engineering), adding a bit more content in the current intro. I am not at all an expert on this, I just thought that such a structure would be good.

For a dedicated subsection, I think it would be better to get suggestions from an expert.

2024-07-01 06:31 UTC, mhagdorn commented on competencies.md
> +RSEs are competent in requirements analysis, design, construction, testing, analysis, and testing of software.
```suggestion
RSEs are competent in requirements analysis, design, construction, and testing of software.
```

Too much testing and analysis

2024-07-01 08:11 UTC, MakisH commented on competencies.md
> +RSEs are competent in requirements analysis, design, construction, testing, analysis, and testing of software.
That was definitely a typo, thanks!

2024-07-07 19:37 UTC, MakisH commented
I quickly drafted a subsection on the classical software engineering skills, based on this table from the SWEBOK, without looking into details how they mean each KA. But I guess this is not too far from the intended.

![Screenshot from 2024-07-07 21-28-34](https://github.com/the-teachingRSE-project/competencies/assets/4943683/9b2d6468-09ca-4847-b667-3978166b8f38)

@jpthiele please check and extend if needed.

2024-07-08 08:01 UTC, jpthiele commented on competencies.md
> +competencies in both fields. RSEs have a background both in research and
I don't think background is the right word here since most have their background in one of both. 
Maybe something along the lines of

"RSEs typically have a background in research or software engineering but have obtained broader knowledge in both fields"

2024-07-15 09:00 UTC, MakisH commented on competencies.md
> +and automate operations of the integration and release process. They are engineers that can
Let's not use the naked "engineering"/"engineers" term lightly, since in Germany, people assume certified Mechanical Engineer or similar.

2024-07-15 09:39 UTC, MakisH commented
I applied the feedback from today, ready for review again.

2024-07-15 11:56 UTC, CaptainSifff reviewed
Not sure about the length, but I would maybe name the subsubsection as "relation to classical software engineering skills".  And then, I kind of miss a hint, that some of these swebok skills we have put into the other pillars. I think we might need to move this subsection below the foundational RSE competencies.  Also I wonder what we do with the slight duplication, e.g. is the docbb skill not already in the "they are competent in implementing..."

2024-07-15 13:46 UTC, mhagdorn commented
I've played around with the order a little and undid some of @MakisH changes to keep the intro to Section 4 shorter. I have introduced a "Relationship to SE" Section 4.1. It all does feel a little repetitious. Maybe we should sort out #291 first as that goes into the intro. We can then cut out some of the repetitions in Section 4.

Anyway, my changes are in branch https://github.com/the-teachingRSE-project/competencies/tree/fix-288-mh which goes on top of this branch.

2024-07-18 17:17 UTC, knarrff commented
I think we may want to discuss this again at a meeting. The new text would shift the definition from "an RSE is somewhere in the spectrum from R...SE to an RSE is close to SE, as it says "An RSE is also an SE" (which many people identifying as RSE might object to) and also things like "research software engineers are also competent software engineers.
As such, they solve complex software engineering problems, and design software as a user-oriented, future-proof product.". Some RSEs surely are at such a level, many are not and would feel excluded. This is essentially again the question whether to consider "researchers who code" as RSEs. I certainly do.

2024-07-18 20:18 UTC, MakisH commented
@knarrff I can certainly refine the text to make it more inclusive. This was written with the intention to strengthen the software engineering character of an RSE, as this was previously pointed out to be weak. I can write it in the lines of "many do, but not everyone".

I will try to do this over the weekend, but I will not be there on the meeting this Monday (conference). Let's keep the arguments documented here, I think we also make progress faster like this.

2024-07-22 05:36 UTC, jpthiele commented on competencies.md
> +Because they stand between fields, RSEs are stronger in topics more commonly
maybe "are often stronger in topics more commonly..."?

2024-07-22 05:37 UTC, jpthiele approved these changes

2024-07-22 19:19 UTC, CaptainSifff commented
I looked at this together with the PR by @mhagdorn and I feel that his changes provided the counterweight that I needed here.

2024-07-25 07:37 UTC, knarrff commented on competencies.md
> +encountered in research software contexts (e.g., mathematical and engineering foundations)
Can we add something from outside STEM here, to be more inclusive?

2024-07-25 07:43 UTC, knarrff commented on competencies.md
> +Finally, as skilled scientists seasoned in computing applications, they have strong mathematical, computing, and engineering foundations,
I think this is too strong. There are a lot of RSEs that don't need that much of math - since their research does not involve much math in the first place. They wouldn't call it 'computing' either, as they might not compute that much, but for instance deal with large amounts of text or images.
In addition, if we leave in the last part of the sentence ("to the degree every SE needs to have"), then this essentially says: you better are on the same level as someone with an SE degree to be an RSE - excluding large parts of our community.
Thus, I do vote to drop this entire sentence ("Finally ... until the end")

2024-07-25 07:44 UTC, mhagdorn commented on competencies.md
> +Because they stand between fields, RSEs are stronger in topics more commonly
the rather cool project of managing audience participation during a concert presented at the deRSE conf springs to mind.

Although I think here the point is that SWEBOK puts maths and algo design as optional skill for a 'normal' SE and one of the distinguishing factors is that an RSE is probably naturally more clued up about those.

2024-07-25 07:45 UTC, knarrff requested changes
... as per my comment on the last sentence.

2024-07-25 07:51 UTC, mhagdorn commented on competencies.md
> +encountered in research software contexts (e.g., mathematical and engineering foundations)
the rather cool project of managing audience participation during a concert presented at the deRSE conf springs to mind.

Although I think here the point is that SWEBOK puts maths and algo design as optional skill for a 'normal' SE and one of the distinguishing factors is that an RSE is probably naturally more clued up about those.

2024-07-25 08:38 UTC, CaptainSifff commented on competencies.md
> +encountered in research software contexts (e.g., mathematical and engineering foundations)
https://en.wikipedia.org/wiki/Formal_language

2024-07-25 08:49 UTC, mhagdorn commented on competencies.md
> +encountered in research software contexts (e.g., mathematical and engineering foundations)
I think we should keep this as those two items are contrasted with SE economics

2024-07-25 09:03 UTC, CaptainSifff commented on competencies.md
> +Finally, as skilled scientists seasoned in computing applications, they have strong mathematical, computing, and engineering foundations,
```suggestion
Finally, as skilled scientists seasoned in computing applications, they have strong mathematical, computing, and engineering foundations,
```
Finally, as skilled researchers they combine the necessary foundations from their domain with software engineering for their applications.

2024-07-25 09:09 UTC, CaptainSifff commented on competencies.md
> +to the degree every software engineer needs to have to develop complex software projects.
```suggestion
```

2024-07-25 09:24 UTC, CaptainSifff commented on competencies.md
> +On the other hand, RSEs also know how to make research software adhere to the \ac{FAIR} principles,
```suggestion
On the other hand, RSEs also know how to make research software adhere to (FAIR4RS [@FAIR4RS]) principles,
```

2024-07-25 09:27 UTC, CaptainSifff commented on competencies.md
> +On the other hand, RSEs also know how to make research software adhere to the (FAIR4RS [@FAIR4RS]) principles,
```suggestion
On the other hand, RSEs also know how to make research software adhere to the \ac{FAIR} principles [@FAIR4RS],
```

2024-07-25 09:29 UTC, knarrff approved these changes

2024-07-25 09:46 UTC, CaptainSifff commented on competencies.md
> +distribute these competencies over the three categories to reflect the fact
```suggestion
distribute these competencies over the three pillars to reflect the fact
```

2024-07-25 09:46 UTC, CaptainSifff commented on competencies.md
> +Section @sec:software-skills). The third categories (communication skills,
```suggestion
Section @sec:software-skills). The third category (communication skills,
```

2024-07-25 09:55 UTC, merged

2024-07-25 15:02 UTC, MakisH commented
Thank you all for wrapping this up without me, and sorry that I could not be more active this week to apply the latest feedback (good morning from WCCM2024). Looks very good! :+1: