Suggested edits and minor updates from full review of the paper.
the-teachingRSE-project/competencies pull request #347
Opened 2024-08-08 20:25 UTC by jcohen02

2024-08-08 23:49 UTC, CaptainSifff requested changes

2024-08-08 23:49 UTC, CaptainSifff commented on competencies.md
> +research data.
I think we have to work a bit harder, if we rewrite this part. The original meaning was, since RSEs do data, processing, and visualization, and science often does this, too, the competencies are important. And this fact has also  been recognised by the funders.

2024-08-08 23:49 UTC, CaptainSifff commented on competencies.md
> +RSEs are highly-skilled software engineers, in addition to having an
ah... I think here we switch meaning.....

2024-08-08 23:49 UTC, CaptainSifff commented on competencies.md
> +Finally, as people who have often gained significant experience of research
here, too...

2024-08-08 23:49 UTC, CaptainSifff commented on competencies.md
> +peers and provide opportunities for lifelong learning.
We have a second use of it around line 1429. and then we can discuss how we spell life-cycle....

2024-08-09 08:14 UTC, jpthiele commented on competencies.md
> +will have a decisive impact on the adequacy for purpose [@bokulich_data_2021] of the model.
```suggestion
will have a significant impact on the adequacy for purpose [@bokulich_data_2021] of the model.
```

Otherwise we have three repetitions of words stemming from decide in close succession

2024-08-09 08:17 UTC, jpthiele commented on competencies.md
> +similar rules for research software (FAIR4RS [@FAIR4RS]).
```suggestion
Here, specifically, they closely interact with research data management professionals
and practices by designing research software 
that is better able to adhere to the \ac{FAIR} principles for research data,
but also to follow similar rules for research software (FAIR4RS [@FAIR4RS]).
```

SemBr

2024-08-09 08:18 UTC, jpthiele commented on competencies.md
> +Data protection is a complex topic, so RSEs should be aware of when they may need to consult external expertise, for example when dealing with
```suggestion
Data protection is a complex topic, so RSEs should be aware that they may need to consult external expertise, for example when dealing with
```

2024-08-09 08:20 UTC, jpthiele commented on competencies.md
> +RSEs are highly-skilled software engineers, in addition to having an
Yes, the two sides of a coin problem again...

2024-08-09 08:50 UTC, mhagdorn approved these changes

2024-08-09 08:50 UTC, mhagdorn commented on glossary.tex
> +\newglossaryentry{bus-factor}{name={bus factor},description={vulnerability of a project to losing team members - a bus factor of 1 means that only a single team member knows the details of the projec
great addition

2024-08-09 08:56 UTC, MakisH commented on competencies.md
> +Jena and deRSE24 in Würzburg, Germany),
```suggestion
Jena, and deRSE24 in Würzburg, Germany),
```

2024-08-09 08:56 UTC, MakisH commented on competencies.md
> +impact beyond the domain of RSE into adjacent aspects of research such as
```suggestion
impact beyond the domain of RSE into adjacent aspects of research, such as
```

2024-08-09 08:56 UTC, MakisH commented on competencies.md
> +research data.
I see the same meaning in the rewritten part.
Maybe only remove the "For example", as this is really the main point, not an example.

2024-08-09 08:56 UTC, MakisH commented on competencies.md
> +For example, this is especially important given that much research involves some amount of
```suggestion
This is especially important given that much research involves some amount of
```

2024-08-09 08:56 UTC, MakisH commented on competencies.md
> -- Principal RSE: Their actual job description varies a lot. These may be RSE team leaders based in a professional services type role, or they may be professors or research group leaders based in a mo
Why this change?

2024-08-09 09:29 UTC, jcohen02 commented on competencies.md
> +peers and provide opportunities for lifelong learning.
Re lifecycle (life cycle?), this was actually in my original notes that I made when reading through, but I decided this was going to result in a lot of changes and maybe it was better to leave it, so I decided to stick with this one instead! 🙂 

(Although if we do want to go down the life cycle route, I think it should probably be "lifecycle"!)

2024-08-09 11:42 UTC, knarrff commented on glossary.tex
> +\newglossaryentry{bus-factor}{name={bus factor},description={vulnerability of a project to losing team members - a bus factor of 1 means that only a single team member knows the details of the projec
```suggestion
\newglossaryentry{bus-factor}{name={bus factor},description={vulnerability of a project to losing key and irreplaceable team members - a bus factor of 1 means that already a single such team member vanishing would stall the project's advancement.}}
```

2024-08-09 11:46 UTC, knarrff commented on competencies.md
> +This prevalence of computation in research means that
```suggestion
This prevalence of computation and digitally aided data analysis in research means that
```

2024-08-09 11:48 UTC, knarrff commented on competencies.md
> +largely by Research Software Engineers (deRSE23 in Paderborn, un-deRSE23 in
```suggestion
largely by RSEs (deRSE23 in Paderborn, un-deRSE23 in
```

2024-08-09 11:49 UTC, knarrff commented on competencies.md
> +Jena, and deRSE24 in Würzburg, Germany),
```suggestion
Jena, and deRSE24 in Würzburg, all in Germany),
```

2024-08-09 12:03 UTC, knarrff commented on competencies.md
> +RSEs are highly-skilled software engineers, in addition to having an
Yes: please do not change the "direction" here.

2024-08-09 12:23 UTC, jcohen02 commented on competencies.md
> +Central to the \ac{SE} Code of Ethics is the RSE's obligation to
```suggestion
It is important that the activities of an RSE are guided by ethical values.
In addition to the values for good scientific practice [@dfg_gsp], RSEs also adhere to
the \ac{SE} Code of Ethics [@Gotterbarn1999].
Central to that code is the RSE's obligation to
In addition to the values for good scientific practice
```

2024-08-09 12:29 UTC, knarrff commented on competencies.md
> +Finally, as people who have often gained significant experience of research
```suggestion
Finally, as people who have often gained significant research experience
```

2024-08-09 12:41 UTC, CaptainSifff commented on competencies.md
> +RSEs are highly-skilled software engineers, in addition to having an
maybe leave it as it was...

2024-08-09 12:45 UTC, CaptainSifff commented on competencies.md
> +Finally, as people who have often gained significant experience of research
the other's like the new version better.

2024-08-09 13:10 UTC, jcohen02 commented on competencies.md
> +| \gls{TEAM}       | Should be able to work in the team in order to effectively fulfil the given tasks. Should be able to learn from code review.  | Should be able to break down tasks into more easil
```suggestion
| \gls{TEAM}       | Should be able to work in the team in order to effectively fulfil the given tasks. Should be able to learn from code review.  | Should be able to break down tasks into more easily digestible sub-tasks and review or guide work undertaken by less-experienced team members.                                                             | Should be able to lead the team and set the respective direction.                                                                                                                   |
```

2024-08-09 13:12 UTC, jcohen02 commented on competencies.md
> +They are able to guide students and prepare and deliver full-length lectures (\gls{TEACH}).
```suggestion
They are able to guide students and prepare and deliver a full lecture course (\gls{TEACH}).
```

2024-08-09 13:14 UTC, jcohen02 commented on competencies.md
> +  research software - often primarily a researcher, but learning and applying RSE skills with focus on their own research. Often time-constrained,
Revert to original:
```suggestion
research software - often an RSE with focus on their own research. Often time-constrained,
```

2024-08-09 18:12 UTC, jcohen02 commented on competencies.md
> +understanding of the research environment.
Reverting this to the original text based on the meeting discussion.
```suggestion
Besides skilled researchers, RSEs are also competent software engineers.
```

2024-08-09 18:12 UTC, jcohen02 commented on competencies.md
> -- Principal RSE: Their actual job description varies a lot. These may be RSE team leaders based in a professional services type role, or they may be professors or research group leaders based in a mo
As discussed in the meeting, it's mentioned in a previous sentence in this paragraph that princpal RSEs may be team/group leaders so this is a repetition.

2024-08-09 18:14 UTC, jcohen02 commented on glossary.tex
> +\newglossaryentry{bus-factor}{name={bus factor},description={vulnerability of a project to losing team members - a bus factor of 1 means that only a single team member knows the details of the projec
Applying suggested update from @knarrff:
```suggestion
\newglossaryentry{bus-factor}{name={bus factor},description={vulnerability of a project to losing key and irreplaceable team members - a bus factor of 1 means that a single such team member vanishing would already stall the project's advancement.}}```

2024-08-09 18:15 UTC, jcohen02 commented on glossary.tex
> +\newglossaryentry{bus-factor}{name={bus factor},description={vulnerability of a project to losing team members - a bus factor of 1 means that only a single team member knows the details of the projec
This suggestion got outdated by a previous suggestion to the same line - I've added it manually.

2024-08-09 18:18 UTC, jcohen02 commented
@CaptainSifff, I've made the edits discussed in today's meeting - I think this should now be ready to merge. Feel free to go ahead if you want to merge, otherwise I can do it tomorrow.

2024-08-09 18:50 UTC, CaptainSifff approved these changes
I will fix some minor thing in master.

2024-08-09 18:51 UTC, merged