Yvgrossmann feedback
the-teachingRSE-project/competencies pull request #349
Opened 2024-08-09 15:39 UTC by CaptainSifff

I did it!

2024-08-09 15:41 UTC, CaptainSifff commented
@ljgarcia What's your idea, do you feel that your paper: https://zenodo.org/records/10374839 makes sense here? From looking over it, It felt more like a report of a productive hackathon, then a  collection of current best practice. Also pinging your colleague @yvgrossmann .

2024-08-09 16:18 UTC, knarrff requested changes

2024-08-09 16:18 UTC, knarrff commented on competencies.md
> +RSEs may work within one of the increasing numbers of research software engineering teams that
Hatten wir das nicht erst andersrum geändert? Es sollte Einzahl sein, also die Änderung würde ich als falsch empfinden.

2024-08-09 16:18 UTC, knarrff commented on competencies.md
>  management for research software (including information on e.g., licenses,
```suggestion
management for research software (including information on, e.g., licenses,
```

2024-08-09 16:18 UTC, knarrff commented on competencies.md
> +actively during, within and after a research project to edify the decision-making
```suggestion
actively during, within, and after a research project, to edify the decision-making
```

2024-08-09 17:56 UTC, CaptainSifff commented on competencies.md
> +RSEs may work within one of the increasing numbers of research software engineering teams that
hab's mal geändert.

2024-08-10 06:33 UTC, jpthiele approved these changes

2024-08-10 21:54 UTC, jcohen02 approved these changes
I've made one minor suggestion but happy to approve nonetheless, this looks fine to me.

2024-08-10 21:54 UTC, jcohen02 commented on competencies.md
> +actively during, within, and after a research project, to edify the decision-making
Minor suggestion:
```suggestion
actively during, within, and after completion of a research project, to edify the decision-making
```

2024-08-11 07:19 UTC, MakisH commented on competencies.md
> +actively during, within, and after a research project, to edify the decision-making
I am not sure I understand the difference between:
- used during a project
- used within a project

Doesn't `within` imply `during`, and `during` imply `within`, given that we are only talking about the project and not any external system?

2024-08-11 08:36 UTC, jpthiele commented on competencies.md
> +actively during, within, and after a research project, to edify the decision-making
My best guess would be that `during` refers to the people in the project processing the metadata mentally while `within` means that the software itself makes use of the metadata. But I agree that it is something that makes one stumble when reading.

2024-08-11 08:37 UTC, mhagdorn commented on competencies.md
> +actively during, within, and after a research project, to edify the decision-making
I agree it is somewhat redundant. However, I wanted to emphasise that using metadata during the project to help direct the project is a real benefit. Typically, the common view is that metadata is collected for follow on projects or other users of the project. The metadata is then like a tombstone: _here lies.... RIP_

2024-08-11 08:38 UTC, jpthiele commented on competencies.md
> +actively during, within, and after a research project, to edify the decision-making
True.. But would we need both during and within then?

2024-08-11 08:44 UTC, mhagdorn commented on competencies.md
> +actively during, within, and after a research project, to edify the decision-making
ah, I missed the last bit, _edify the project_. I don't like this phrase, it has religious connotations to me. I prefer the original inform the decision making as that's more neutral.

2024-08-11 08:48 UTC, mhagdorn commented on competencies.md
> +actively during, within, and after completion of a research project, to edify the decision-making
```suggestion
actively during and within a research project, to inform the decision-making
```
I would prefer my original wording. Metadata is usually collected for use after completion of the project. So that conflicts with the _also_. The point is that metadata can be used while the project is active (during) for purposes of the project (within).

2024-08-11 18:34 UTC, merged