New acknowledgements
the-teachingRSE-project/competencies pull request #350
Opened 2024-08-09 17:41 UTC by CaptainSifff

Oh well, I looked into the Credit system again, and I only thought....
Well, how  does this fit to us?
So I wrote a generic text to tick that box, and went on to detail those parts that I could remember, which you have contributed over the past years.
Feel free to raise your opinions.

I also accept private E-Mail, if I took a wrong direction somewhere....

Now comes the pleasure of finding all your github usernames ....

2024-08-09 17:45 UTC, CaptainSifff commented
Pinging @sdruskat , @tobyhodges @annalenalamprecht , @HeidiSeibold , @hvwaldow , @samumantha 
As I found out there's a limit of 15 reviewers on github....

2024-08-09 17:55 UTC, jngrad commented
I predict there will be a lot of small changes during review. In order to reduce notifications, we could apply suggested changes in batches, i.e. 1 commit for multiple review comments. :wink: This option is only visible in the Changes tab, afaik.

2024-08-09 17:58 UTC, CaptainSifff commented
the spell-checker will be made happy by the PR of @jcohen02 .

2024-08-09 18:15 UTC, jngrad commented on competencies.md
> +Anna-Lena Lamprecht helped us to use proper wording and make us aware, where we are misusing established SE terms.
```suggestion
Anna-Lena Lamprecht helped us to use proper wording and made us aware, where we were misusing established SE terminology.
```

2024-08-09 18:15 UTC, jngrad commented on competencies.md
> +Frank Löffler rewrote numerous parts to be actually legible, and helped us in steering onto the final meters for a de-RSE position paper.
is "final meters" used outside of sports? I could certainly be wrong, but in the context of project management, "the last mile" and "the final stretch" feel more natural to me.

2024-08-09 18:15 UTC, jngrad commented on competencies.md
> +the CRediT system is far to generic to adequately describe the contributions of everybody.
```suggestion
the CRediT system is far too generic to adequately describe the contributions of everybody.
```

2024-08-09 18:17 UTC, CaptainSifff commented on competencies.md
> +the relationship of the RSE competencies to the SE competencies.
Great point, and gives us the opportunity to reference it again!

2024-08-09 18:23 UTC, CaptainSifff commented on competencies.md
> +Frank Löffler rewrote numerous parts to be actually legible, and helped us in steering onto the final meters for a de-RSE position paper.
:-) Yes, you're right. Additionally it's a literal german translation, since we don't have last miles . Will change!

2024-08-09 20:14 UTC, mhagdorn requested changes
expanded  shortened verbs

2024-08-09 20:14 UTC, mhagdorn commented on competencies.md
> +Maybe it's obvious, but as you can guess from having various workshops
```suggestion
Maybe it is obvious, but as you can guess from having various workshops
```

2024-08-09 20:14 UTC, mhagdorn commented on competencies.md
> +And, most likely, without him, we wouldn't have a bibliography at all.
```suggestion
And, most likely, without him, we would not have a bibliography at all.
```

2024-08-10 06:15 UTC, jpthiele commented on competencies.md
>  Heidi Seibold, Jeremy Cohen, Florian Goth, Renato Alves, Jan Philipp Thiele,
Do we maybe want to change this sentence and the previous, it feels weirdly ordered at the moment with idea, thank participants, organisers.

2024-08-10 06:33 UTC, jpthiele approved these changes

2024-08-10 13:12 UTC, CaptainSifff commented on competencies.md
>  Heidi Seibold, Jeremy Cohen, Florian Goth, Renato Alves, Jan Philipp Thiele,
technically you can say parts of it are redundant. But I didn't want to waste any opportunity to thank our participants....

2024-08-10 13:21 UTC, CaptainSifff commented on competencies.md
>  Heidi Seibold, Jeremy Cohen, Florian Goth, Renato Alves, Jan Philipp Thiele,
2195922 now has that changed. How about it?

2024-08-10 14:52 UTC, jpthiele commented on competencies.md
>  Heidi Seibold, Jeremy Cohen, Florian Goth, Renato Alves, Jan Philipp Thiele,
No, having thanks for each workshop is certainly good!

2024-08-10 16:46 UTC, mhagdorn commented on competencies.md
> +Fredo Erxleben contributed to early discussions of the paper and contributed the efforts done by Helmholtz.
```suggestion
Fredo Erxleben contributed to early discussions of the paper and added the contributions by the Helmholtz Association.
```

2024-08-10 16:48 UTC, mhagdorn commented on competencies.md
> +Jan Linxweiler drafted various RSE specialisations and made sure that clean coding techniques have their importance.
```suggestion
Jan Linxweiler drafted various RSE specialisations and made sure that clean coding techniques got their due recognition.
```

2024-08-10 16:51 UTC, mhagdorn commented on competencies.md
> +And while everybody contributed to the entirety of the script, some parts bear a personal handwriting.
```suggestion
And while everybody contributed to the entirety of the script, some parts merit special mention.
```

2024-08-10 16:54 UTC, mhagdorn commented on competencies.md
> +the CRediT system is far too generic to adequately describe the contributions of everybody.
I had to look up CRediT, I think we might need a reference here. Otherwise we should reformulate this sentence without mentioning it.

2024-08-10 17:23 UTC, CaptainSifff commented on competencies.md
> +the CRediT system is far too generic to adequately describe the contributions of everybody.
Now we have a reference.

2024-08-10 18:30 UTC, mhagdorn commented on competencies.md
> +the CRediT system is far too generic to adequately describe the contributions of everybody.
fabby

2024-08-10 21:20 UTC, jcohen02 commented on competencies.md
> +Samantha Wittke contributed the parts on CodeRefinery and how to reach out to beginning RSEs.
I think you probably want to say "new" rather than "beginning":
```suggestion
Samantha Wittke contributed the parts on CodeRefinery and how to reach out to new RSEs.
```
...or, if you wanted to extend this further, you maybe could say "_...and how to reach out to new RSEs who have recently joined the community._"?

2024-08-10 21:22 UTC, jcohen02 approved these changes
Thanks for your work preparing these very detailed acknowledgements @CaptainSifff 👍. Aside from the one comment I added above, I'm happy with the parts relate to me so approving the PR.

2024-08-11 06:49 UTC, MakisH commented on competencies.md
> +Jeremy Cohen drafted the initial introduction and contributed the tables for RSEs in centralised RSE departments(Jean-Noël Grad made them render properly).
@CaptainSifff @jngrad not sure what you refer to here, but I invested some effort here... :sweat_smile:  https://github.com/the-teachingRSE-project/competencies/pull/184

2024-08-12 05:35 UTC, knarrff commented on competencies.md
> +the CRediT system [@Brand2015] is far too generic to adequately describe the contributions of everybody.
```suggestion
The CRediT system [@Brand2015] is far too generic to adequately describe the contributions of everybody in various workshops, spread over a two year period.
```

2024-08-12 05:35 UTC, knarrff commented on competencies.md
> +And while everybody contributed to the entirety of the script, some parts merit special mention.
While everybody contributed to the entirety of the script, some parts merit special mention.
```

2024-08-12 05:36 UTC, knarrff commented on competencies.md
> +Maybe it is obvious, but as you can guess from having various workshops
```suggestion
```

2024-08-12 05:36 UTC, knarrff commented on competencies.md
> +spread out over a two year period, and a total list of 23 authors
```suggestion
```

2024-08-12 05:37 UTC, knarrff commented on competencies.md
> +And while everybody contributed to the entirety of the script, some parts merit special mention.
```suggestion
While everybody contributed to the entirety of the script, some parts merit special mention.
```

2024-08-12 05:42 UTC, knarrff commented on competencies.md
> +Simon Christ helped us with typesetting, contributed the competencies' symbols, and the spell-checker script.
```suggestion
Simon Christ helped with typesetting, contributed the competencies' symbols, and the spell-checker script.
```

2024-08-12 05:44 UTC, knarrff commented on competencies.md
> +Anna-Lena Lamprecht helped us to use proper wording and made us aware, where we were misusing established SE terminology.
```suggestion
Anna-Lena Lamprecht helped with proper wording and especially made us aware, where we were misusing established SE terminology.
```

2024-08-12 05:47 UTC, annalenalamprecht commented
I cannot find it back right now, but @MakisH pointed out earlier that "helped us" (and similar wording) sounds a bit odd when mentioning people who are also on the list of authors. Simply removing the "us" from these sentences would solve the issue.

2024-08-12 05:50 UTC, knarrff commented on competencies.md
> +Florian Goth has the pleasure of being grateful to all collaborators in this project for contributing their time and knowledge into this project over the past two years!
```suggestion
Florian Goth has the pleasure of being grateful to all collaborators in this project for contributing their time and knowledge into this project over the span of  two years!
```

2024-08-12 05:50 UTC, knarrff commented on competencies.md
> +Florian Goth has the pleasure of being grateful to all collaborators in this project for contributing their time and knowledge into this project over the past two years!
While "the past two" is correct now, it will read a little odd in 5 years time.

2024-08-12 05:51 UTC, knarrff approved these changes

2024-08-12 05:54 UTC, knarrff commented
Closes: #333

2024-08-12 06:10 UTC, MakisH commented on competencies.md
> +And while everybody contributed to the entirety of the script, some parts bear a personal handwriting.
I have the impression this was unintentionally marked as "resolved", without discussion.

2024-08-12 06:21 UTC, MakisH commented on competencies.md
> +Frank Löffler rewrote numerous parts to be actually legible, and helped us in steering onto the final meters for a de-RSE position paper.
"last steps" would surprise nobody in this context, I think (unless you want to emphasize that these were too many or large steps).

2024-08-12 06:53 UTC, mhagdorn commented on competencies.md
> +Florian Goth has the pleasure of being grateful to all collaborators in this project for contributing their time and knowledge into this project over the past two years!
maybe just leave out _over the past two years_ since we are not done yet.

2024-08-12 08:16 UTC, MakisH commented on competencies.md
> +While everybody contributed to the entirety of the script, some parts merit special mention.
```suggestion
While everybody contributed to the discussion formulating and refining the ideas, and to collaboratively writing and/or reviewing and editing the entirety the script, some parts merit special mention.
```

2024-08-12 08:18 UTC, MakisH commented on competencies.md
> +And while everybody contributed to the entirety of the script, some parts bear a personal handwriting.
Added again a suggestion in the latest state of the code: https://github.com/the-teachingRSE-project/competencies/pull/350/files#r1713336643

Resolving this thread.

2024-08-12 08:22 UTC, jpthiele commented on competencies.md
> +of this work.
```suggestion

```
Move to `acknowledgements.md`

2024-08-12 08:32 UTC, jpthiele commented on competencies.md
> +Leyla Jael Castro contributed to the initial draft of the example career path, and helped us in discussions on metadata.
```suggestion
Leyla Jael Castro contributed to the initial draft of the example career path, and provided helpful insights in discussions on metadata.
```

2024-08-12 08:34 UTC, jpthiele commented on competencies.md
> +Anna-Lena Lamprecht helped with proper wording and especially made us aware, where we were misusing established SE terminology.
```suggestion
Anna-Lena Lamprecht helped with proper wording, especially with awareness about established SE terminology, that was misued earlier.
```

2024-08-12 08:34 UTC, jpthiele commented on competencies.md
> +Frank Löffler rewrote numerous parts to be actually legible, and helped us in preparing for the last mile of a de-RSE position paper.
```suggestion
Frank Löffler rewrote numerous parts to be actually legible, and helped with preparation for the final steps of a de-RSE position paper.
```

2024-08-12 08:36 UTC, mhagdorn commented on competencies.md
> +Leyla Jael Castro contributed to the initial draft of the example career path, and helped us in discussions on metadata.
I think this should be insights _to_

2024-08-12 08:42 UTC, mhagdorn commented on competencies.md
> +Anna-Lena Lamprecht helped with proper wording, especially with awareness about established SE terminology, that was misued earlier.
```suggestion
Anna-Lena Lamprecht helped with proper wording, especially with awareness about established SE terminology, that was missed earlier.
```
fix typo

2024-08-12 08:50 UTC, MakisH commented on competencies.md
> +Jeremy Cohen drafted the initial introduction and contributed the tables for RSEs in centralised RSE departments(Jean-Noël Grad made them render properly).
We addressed this by extending the overall technical contribution of @jngrad and removing the parenthesis regarding the formatting of the tables.

2024-08-12 08:59 UTC, jngrad commented on competencies.md
> +Jeremy Cohen drafted the initial introduction and contributed the tables for RSEs in centralised RSE departments(Jean-Noël Grad made them render properly).
He was referring to #19. This was a collaborative effort, where my contributions were limited to advocating for using LaTeX rather than HTML and figuring out which LaTeX typos were crashing the LaTeX processor.

2024-08-12 09:58 UTC, jngrad commented on acknowledgements.md
The sentence was moved from the stand-alone file to the metadata section of the competencies.md paper (like we did for the abstract). The Python script adds this metadata to the list of acknowledgements.

2024-08-12 09:59 UTC, jngrad approved these changes

2024-08-12 10:59 UTC, MakisH approved these changes

2024-08-12 18:12 UTC, CaptainSifff commented
I'm beginning the publication process, thereby closing this box as of now.

2024-08-12 18:13 UTC, merged

2024-08-12 18:57 UTC, sdruskat commented
Thanks for the ping, I‘ll get to review this week (before Friday).