introduce more additionals
the-teachingRSE-project/competencies pull request #351
Opened 2024-08-09 19:13 UTC by CaptainSifff

I introduced some more words into the specialization section.

2024-08-10 06:30 UTC, jpthiele commented
It feels like we add *additionally* to almost all specialisations now. Should we not do a general sentence in the beginning of the section instead then?

2024-08-10 11:13 UTC, CaptainSifff commented
hmm, what's you feeling about "specializing into <stuff outside RSE>", since this is already present in some specialization. Does this imply that its something additional? Then I can remove some of them.

2024-08-10 11:37 UTC, jpthiele commented
We already categorize into 'proper' specializations, i.e. taking a deep dive into one of the skills, and those extending their skill set. So I would say it is already clear that they have to have additional skills.

2024-08-10 21:51 UTC, jcohen02 requested changes
The various "additionally" additions look good and provide the change we discussed in the meeting.

I provided a couple of suggestions - one is a rather fundamental point that I've detailed in my comments - it should be a very easy fix, or, if I'm misunderstanding the context then it can stay the same 🙂.

Otherwise all looks fine.

2024-08-10 21:51 UTC, jcohen02 commented on competencies.md
> +These are RSEs working at the flourishing intersection between data science and RSE.
I guess this is OK but when we say "These are", when reading it, it feels a little "impersonal". I might be inclined to say:
```suggestion
Data-focused RSEs work at the flourishing intersection between data science and RSE.
```

2024-08-10 21:51 UTC, jcohen02 commented on competencies.md
> +we believe that the competencies formulated here, centred around data handling, can offer far-reaching
I'm not actually sure about the "centered around data [ processing | handling ]", this has been added since the version I reviewed over the last couple of days and I think it changes the meaning somewhat. I might be missing the context here but the original text read:

> While this community paper is based on workshop discussions that were attended largely by Research Software Engineers (deRSE23 in Paderborn, un-deRSE23 in Jena, Germany), we believe that the competencies formulated here can offer far-reaching impact beyond the domain of RSE into adjacent fields of science...

This effectively says that while the majority of the people who participated in the discussions leading to this paper were RSEs we recognise that the competencies developed here have a much wider potential for impact across areas including data (and perhaps research computing infrastructure?).

As I understand it, the addition of "_...centred around data processing..._" has changed the meaning to say that the competencenies we have formulated here, while developed by a group largely made up of RSEs, are actually centred around data - I don't agree with that, they cover a whole range of areas across software, research and communication - while it's only a few additional words, it's quite early on in the core introductory material and I think it changes the focus of the paper.

Apologies if I'm misunderstanding, but if I am understanding this correctly, I'd suggest reverting to the original text:
```suggestion
we believe that the competencies formulated here can offer far-reaching
```

2024-08-11 07:14 UTC, MakisH commented
Isn't anyway the "being specialized" implying that the specialization comes additionally to the main skills? I don't think we need to say that a nuclear physicist is a physicist who additionally is specialized into nuclear physics.

I don't think we need either the "additionally", nor any additional sentence in the beginning.

2024-08-11 08:31 UTC, jpthiele commented
> Isn't anyway the "being specialized" implying that the specialization comes additionally to the main skills? I don't think we need to say that a nuclear physicist is a physicist who additionally is specialized into nuclear physics. They are simply a physicist specialized in nuclear physics, and remain a physicist anyway.
> 
> I don't think we need either the "additionally", nor any additional sentence in the beginning.

The "additionally" in each specialization felt like too much so my initial response was moving that out. 
But after reading the existing introduction into the specializations section I agree that we do not need it there either.

2024-08-11 20:27 UTC, CaptainSifff commented
OK, now the rule is, if it says RSE in the sentence there is no additional "additional"...

2024-08-11 21:14 UTC, CaptainSifff commented
> The various "additionally" additions look good and provide the change we discussed in the meeting.
> 
> I provided a couple of suggestions - one is a rather fundamental point that I've detailed in my comments - it should be a very easy fix, or, if I'm misunderstanding the context then it can stay the same 🙂.
> 
> Otherwise all looks fine.
> 
> EDIT: I was a little behind with catching up with the above discussion - I see there is actually the suggestion that we have too many "additionally"s and should replace these with a general sentence. I'm happy either way on this so OK to go with the consensus.

@jcohen02, @jpthiele How about the new variant? I brought in the tools creation.

2024-08-12 05:53 UTC, knarrff approved these changes
I am fine either way: there are arguments for both cases (repeating additional or not), but they are all not strong as well. Maybe there is a slight preference for not repeating the 'additional', but that is really only slight.

2024-08-12 06:05 UTC, MakisH approved these changes

2024-08-12 08:07 UTC, merged