Summarized '#sec:rse-specialisations'
the-teachingRSE-project/competencies pull request #375
Opened 2024-10-16 07:41 UTC by CaptainSifff

Considering this section without , the `wc' utility would count 1422 words before this commit and 685 after (737 fewer).

Removed references to @Nieva2020 and @SSIDataScience from the text (these were the only ones(. Kept references to @GDPR, @ExportControl, @FAIR.

I did not make items out of the subsections; this may still be done.

This is for issue #374 aka
 https://github.com/the-teachingRSE-project/competencies/issues/374
aka "Condensed Version of Specializations Section".

2024-10-16 07:42 UTC, CaptainSifff commented
pinging @knarrff and @jpthiele

2024-10-21 11:38 UTC, mhagdorn requested changes
various suggestions with grammar fixes.

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +and involved people in their different roles (e.g. \gls{USERS}, and \gls{TEAM}).
_involved_ is the wrong tense, maybe

```suggestion
and delegating tasks to people in their different roles (e.g. \gls{USERS}, and \gls{TEAM}).
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +Teaching (\gls{TEACH}) the next generation of scientists (RSEs or not) the core RSE skills and yet respecting the domain's culture requires having rudiments in didactics and pedagogy, and prepares th
```suggestion
Teaching (\gls{TEACH}) the next generation of scientists (RSEs or not) the core RSE skills and yet respecting the domain's culture requires being versed in didactics and pedagogy. It prepares the scene for better research software to come.
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +Good software is not only functional, but also has proper documentation (\gls{DOCBB}), is properly distributed (\gls{DIST}, \ac{FAIR}) and is ergonomic (\gls{MOD}).
```suggestion
Good software is not only functional, but is also documented (\gls{DOCBB}) and distributed distributed (\gls{DIST}, \ac{FAIR}). It is also designed with users in mind (\gls{MOD}).
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +Some RSEs devote themselves to these aspects.
I'd just drop this sentence.

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +perhaps anonymizing it (e.g. patient information in medicine),
```suggestion
perhaps anonymising or pseudonymising them (e.g. patient information in medicine).
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +and most often transferring securely and archiving properly \ac{FAIR} [@FAIR].
```suggestion
This role also includes transferring data securely and archiving them properly \ac{FAIR} [@FAIR].
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +Configuring them requires knowledge also in administration, hardware, user management, access permissions (\glspl{SysOp}, \ac{IT}, \ac{ML}).
```suggestion
Configuring these services also requires knowledge in administration, hardware, user management and access permissions (\glspl{SysOp}, \ac{IT}, \ac{ML}).
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +research software tend to be nurtured and passed over generations of researchers,
```suggestion
research software tends to be nurtured and developed by generations of researchers,
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +and often without formalized code management practices (\gls{DIST},...).
```suggestion
often without formalized code management practices (\gls{DIST},...).
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +Experienced RSEs help overcoming deprecated practices and features, if necessary making code leaner and faster,
```suggestion
Experienced RSEs help modernising code, if necessary making it leaner and faster,
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +Web services have to offer users (which may include the public) an usable and accessible interface and yet be functional, interoperable in the provided data formats, and yet offering security and dat
```suggestion
Web services have to offer users (which may include the public) a usable and accessible interface and yet be functional, interoperable in the provided data formats, whilst also offering security and data integrity.
```

2024-10-21 11:38 UTC, mhagdorn commented on summarised_competencies.md
> +As elsewhere, adhering to the values in @sec:values provides guidance.
```suggestion
As elsewhere, they adhere to the values in @sec:values provides guidance.
```

2024-10-28 01:15 UTC, CaptainSifff commented on summarised_competencies.md
> +As elsewhere, adhering to the values in @sec:values provides guidance.
they adhere to X provides guidance, doesn't sound right either....

2024-10-28 01:17 UTC, CaptainSifff commented on summarised_competencies.md
> +Good software is not only functional, but also has proper documentation (\gls{DOCBB}), is properly distributed (\gls{DIST}, \ac{FAIR}) and is ergonomic (\gls{MOD}).
there's a typo in the suggestion.

2024-10-28 01:18 UTC, CaptainSifff commented on summarised_competencies.md
> +and most often transferring securely and archiving properly \ac{FAIR} [@FAIR].
shouldn't it be it?

2024-10-28 09:26 UTC, mhagdorn commented on summarised_competencies.md
> +As elsewhere, adhering to the values in @sec:values provides guidance.
we could just drop that sentence

2024-10-29 08:42 UTC, mhagdorn requested changes
another round of suggestions

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +Most RSEs roles embody a blend of these, and may stretch beyond.
```suggestion
There is a large variety of RSE roles that embody a blend of the basic skills and competencies defined above.
We now list some of these specialisations.
```

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +Open science practices are not only being adopted increasingly, but also required by research funding agencies.
```suggestion
Open science practices are increasingly required by research funding agencies.
```

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +This role may or may not involve programming.
```suggestion
Large research software projects require somebody to take
an overview role, caring about the overall perspective (\gls{PM})
and delegating tasks to project members (e.g. \gls{USERS}, and \gls{TEAM}).
This role may or may not involve programming.
```

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +Teaching (\gls{TEACH}) the next generation of scientists (RSEs or not) the core RSE skills and yet respecting the domain's culture requires being versed in didactics and pedagogy. It prepares the sce
```suggestion
Teaching (\gls{TEACH}) the next generation of scientists (RSEs or not) the core RSE skills while respecting the domain's culture requires being versed in didactics and pedagogy. Educators play
a vital role in improving the quality of research software.
```

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +Good software is not only functional, but also has proper documentation (\gls{DOCBB}), is properly distributed (\gls{DIST}, \ac{FAIR}) and is ergonomic (\gls{MOD}).
hm, I think I must have fixed the typo. At least I cannae spot it.

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +Some RSEs devote themselves to these aspects.
```suggestion
```

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +often without formalized code management practices (\gls{DIST},...).
```suggestion
often without formalized code management practices (\gls{DIST}).
```
drop ellipses

2024-10-29 08:42 UTC, mhagdorn commented on summarised_competencies.md
> +and for compliance with export control regulations (e.g. [@ExportControl] in Germany),
```suggestion
With the advent of data protection regulatory frameworks,
and for compliance with export control regulations,
```
drop examples to reduce number of references

2024-10-30 07:12 UTC, jpthiele commented on summarised_competencies.md
> +Good software is not only functional, but also has proper documentation (\gls{DOCBB}), is properly distributed (\gls{DIST}, \ac{FAIR}) and is ergonomic (\gls{MOD}).
there's a double 'distributed'

2024-10-30 07:12 UTC, jpthiele commented on summarised_competencies.md
> +Some RSEs devote themselves to these aspects.
Agree

2024-10-30 07:13 UTC, jpthiele commented on summarised_competencies.md
> +Most RSEs roles embody a blend of these, and may stretch beyond.
Good suggestion!

2024-10-30 07:13 UTC, jpthiele commented on summarised_competencies.md
> +This role may or may not involve programming.
Good suggestion!

2024-10-30 07:13 UTC, jpthiele commented on summarised_competencies.md
> +Teaching (\gls{TEACH}) the next generation of scientists (RSEs or not) the core RSE skills and yet respecting the domain's culture requires being versed in didactics and pedagogy. It prepares the sce
Good suggestion!

2024-10-30 07:15 UTC, jpthiele commented on summarised_competencies.md
> +and most often transferring securely and archiving properly \ac{FAIR} [@FAIR].
I think data is a difficult one. 
We could maybe disembiguate by writing `data sets`

2024-10-30 07:16 UTC, jpthiele commented on summarised_competencies.md
> +As elsewhere, adhering to the values in @sec:values provides guidance.
Yes, let us drop it

2024-10-30 07:53 UTC, mhagdorn commented on summarised_competencies.md
> +Good software is not only functional, but also has proper documentation (\gls{DOCBB}), is properly distributed (\gls{DIST}, \ac{FAIR}) and is ergonomic (\gls{MOD}).
aha, that's not something the spell checker can find and I am not plugged into an AI (yet?) - updated my suggestion

2024-10-31 16:04 UTC, CaptainSifff commented on summarised_competencies.md
> +As elsewhere, adhering to the values in @sec:values provides guidance.
```suggestion
```

2024-10-31 16:07 UTC, CaptainSifff commented on summarised_competencies.md
> +and most often transferring securely and archiving properly \ac{FAIR} [@FAIR].
```suggestion
This role also includes transferring data sets securely and archiving them properly \ac{FAIR} [@FAIR].
```

2024-10-31 16:15 UTC, CaptainSifff commented on summarised_competencies.md
> +Some RSEs devote themselves to these aspects.
did just that.

2024-10-31 16:16 UTC, CaptainSifff commented on summarised_competencies.md
> +As elsewhere, adhering to the values in @sec:values provides guidance.
did just that.

2024-10-31 16:17 UTC, CaptainSifff commented
I'll merge this, to close the box on this.

2024-10-31 16:18 UTC, merged