a first version of the biography
the-teachingRSE-project/competencies pull request #377
Opened 2024-10-22 17:42 UTC by CaptainSifff

2024-10-24 07:05 UTC, mhagdorn requested changes
some minor bits and bobs

2024-10-24 07:05 UTC, mhagdorn commented on summarised_competencies.md
> +The teachingRSE project has been working on the associated biger publication in FIXME for the past two years.
```suggestion
The teachingRSE project has been working on the associated bigger publication in FIXME for the past two years.
```
fix typo

2024-10-24 07:05 UTC, mhagdorn commented on summarised_competencies.md
> +There was Heidi Seibold who came up with the original idea for the deRSE23 workshop in Paderborn.
a little less conversational maybe
```suggestion
The project was initiated by Heidi Seibold who came up with the original idea for the deRSE23 workshop in Paderborn.
```

2024-10-24 07:05 UTC, mhagdorn commented on summarised_competencies.md
> +Also the group gained more recognition, and the teachingRSE project is now an official working group
```suggestion
The group gained more recognition, and the teachingRSE project is now an official working group 
```

2024-10-24 07:05 UTC, mhagdorn commented on summarised_competencies.md
> +in de-RSE and in the special interest group on research software of the Gesellschaft für Informatik.
```suggestion
of the de-RSE society and the special interest group on research software of the Gesellschaft für Informatik.
```

2024-10-24 07:10 UTC, mhagdorn commented on summarised_competencies.md
> +Over the course of further workshops like the un-deRSE23 workshop in Jena, and the deRSE24 in Würzburg,
What about adding

In addition to the workshops the ideas were further developed  during weekly meetings led by Florian Goth.

2024-10-28 01:13 UTC, CaptainSifff commented on summarised_competencies.md
> +Over the course of further workshops like the un-deRSE23 workshop in Jena, and the deRSE24 in Würzburg,
added text trying to resolve both.

2024-10-28 14:23 UTC, merged